### ISSUE TITLE
Deploy Production

### ISSUE THREAD

**Issue by Shama95** [Shama95/GenTlushim#26]
<div dir=rtl markdown=1>
אחרי ששי כותב WIKI על איך לעשות:<br/>
להוסיף את ענף המסטר לheroku<br/>
להוסיף את ענף הdevelopment לheruko<br/>
<br/>
ככל שתסיים יותר מהר ככה נוכל לבדוק את הפרוד שלנו.<br/>
אם אתה צריך עזרה תיעזר בשי.

**Comment by Shama95** [comment]
פרוד - מקושר לענף master:
https://gen-tlushim-scr.herokuapp.com/
פיתוח - מקושר לענף development:
https://gen-tlushim-dev.herokuapp.com/

כרגע הדפים האלה פחות או יותר ריקים - כנראה צריך לעשות merge אליהם מכל הענפים הצדדיים.

**Comment by AvivLevi815** [comment]
פרוד - מקושר לענף master:
https://gen-tlushim-scr.herokuapp.com/
פיתוח - מקושר לענף development:
https://gen-tlushim-dev.herokuapp.com/

כרגע הדפים האלה פחות או יותר ריקים - כנראה צריך לעשות merge אליהם מכל הענפים הצדדיים.
